version: '3'
services:
  server:
    container_name: "demo-server"
    build:
      context: ./server
      dockerfile: Dockerfile
    command: npm run dev
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
    network_mode: "host"

  client:
    container_name: "demo-client"
    build:
      context: ./client
      dockerfile: Dockerfile
    command: npm run start
    volumes:
      - ./client:/app
      - /app/node_modules
    network_mode: "host"

